require("./css/bootstrap.css")
require("./css/styles.css")
require("./js/jquery-3.2.1.min.js")
require("./js/bootstrap.js")
require('./index.html')
require('./inputgroups.html')
require('./templates/progressbars.html')
